spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/usersdb

server:
  port: 8081

after:
  log:
    level:
      org.springframework: INFO
