<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.3</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>com.preparation</groupId>
    <artifactId>learning-spring</artifactId>
    <version>1.0.0</version>
    <name>preparation</name>
    <description>Demo project for Spring Boot</description>
    <packaging>pom</packaging>
	
    <properties>
        <java.version>24</java.version>
        <spring-boot.version>3.5.3</spring-boot.version>
        <spring-framework.version>6.1.4</spring-framework.version>
        <maven.compiler.release>24</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <spring-boot.maven.plugin.version>3.5.3</spring-boot.maven.plugin.version>
        <spring-boot.loader.version>3.5.3</spring-boot.loader.version>
        <spring-boot.loader.tools.version>3.5.3</spring-boot.loader.tools.version>
        <spring-boot.loader.classpath.version>3.5.3</spring-boot.loader.classpath.version>
    </properties>

    <modules>
        <module>rest-example</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
